### ISSUE TITLE
api 형식 

### ISSUE THREAD

**Issue by window9u** [sj030/Tooktak#54]
https://github.com/sj030/Tooktak/blob/b6804e6e7e816d5ccedfbcfe68ca9cac65a0b788/backend/routes/file.js#L21

확인해보니 기존 API의 명칭을 좀 더 RESTful한 방식으로 변경하면 좋을 것 같습니다. 다음과 같이 수정할 수 있습니다:

/getDownloadProgress -> GET file/download/progress
/addPatients -> GET file/patients
/search -> GET file/metadata?query
/addFiles -> 명확한 의미 전달을 위해 추가 정보가 필요합니다. 만약 파일을 업로드하는 것이라면 POST 요청이 적절해보입니다.

rest api 규칙 읽어보고 이름 바꿔주세요. 
동사 대신 HTTP 메소드(GET, POST 등)를 쓰고, url 에는 최대한 명사 써 주세요 이미 get 요청인데 get은 필요가 없죠. 
그리고 download, upload는 헷갈리니까 그렇다 치더라도 동사는 최대한 빼 주세요. add, search 등 다 필요없어 보입니다. 
search -> get 요청 
addFiles는 files경로이미 라우팅 되었는데, 오면 file/addFiles로 요청을 보내야 하는건가요? 
그리고 camel case 말고 /로 구분해 주세요

**Comment by dldyou** [comment]
#56 적용 완료되었습니다.
